### ISSUE TITLE
Base package against continued fork

### ISSUE THREAD

**Issue by Alexmitter** [flathub/org.gtk.Gtk3theme.Arc-Dark#2]
Hello, someone continued the work and added support for things like libhandy widgets, please change to this as the base of the flatpak https://github.com/jnsh/arc-theme

**Comment by jairoraiol** [comment]
Hi!
On this new base for the flatpak: https://github.com/jnsh/arc-theme

I am also looking forward to this change.
Currently, on Flathub, there is no Lighter variant.

Thank you.

**Comment by hossamdash** [comment]
@TingPing 
I hope you look into this when you have time as this fork has support for gtk4 and is currently actively maintained. a lot of flatpak applications are using gtk4 now and it would be nice for arc-dark theme to be applied to them instead of falling back to Adwaita.

**Comment by TingPing** [comment]
This uses the new fork now.  GTK4 is another discussion to add to the runtimes.

**Comment by hossamdash** [comment]
Oh sorry. The old url in the .appdata.xml file threw me off. that should be changed too.

**Comment by TingPing** [comment]
> Oh sorry. The old url in the .appdata.xml file threw me off. that should be changed too.

Updated.
